#ifndef ENUMS_H_INCLUDED
#define ENUMS_H_INCLUDED

// Declarations and definitions of node.h

enum PS3BOOT {
    REBOOT,
    SOFTREBOOT,
    HARDREBOOT,
    SHUTDOWN
};

enum BUZZER {
    SINGLE,
    DOUBLE,
    TRIPLE
};

enum LEDCOLOR {
    RED,
    GREEN,
    YELLOW
};

enum LEDMODE {
    OFF,
    ON,
    BLINKFAST,
    BLINKSLOW
};

enum DELHISTORY {
    EXCLUDE_DIR,
    INCLUDE_DIR
};

enum SYSCALL8MODE {
    ENABLED,
    ONLY_COBRAMAMBA_AND_PS3API_ENABLED,
    ONLY_PS3MAPI_ENABLED,
    FAKEDISABLED,
    DISABLED
};

enum PS3MAPI_RESPONSECODE {
    DATACONNECTIONALREADYOPEN= 125,
    MEMORYSTATUSOK=150,
    COMMANDOK = 200,
    REQUESTSUCCESSFUL = 226,
    ENTERINGPASSIVEMOVE = 227,
    PS3MAPICONNECTED=220,
    PS3MAPICONNECTEDOK =230,
    MEMORYACTIONCOMPLETED = 250,
    MEMORYACTIONPENDING = 350,
    FAIL = 500
};

#endif